### ISSUE TITLE
Release compatible with Python 3.12

### ISSUE THREAD

**Issue by j-bowhay** [rparini/cxroots#374]
Thanks for your work on this package @rparini! I was wondering if you would consider releasing a version on pypi that works with Python 3.12?

**Comment by rparini** [comment]
Hi @j-bowhay no problem, thanks for asking. I've just released [v3.0.1](https://pypi.org/project/cxroots/3.0.1) which is tested on 3.12

**Comment by j-bowhay** [comment]
Thanks for the speedy response @rparini! May I be nosy and ask what kind of problems were you working on that inspired you to write this package?

**Comment by rparini** [comment]
My academic background was in mathematical physics and I was numerically simulating the collision of special kinds of waves called solitons that have particle-like properties with certain boundaries and defects. In order to analyse how these collisions change or split the solitons a kind of nonlinear Fourier transform can be used to decompose the post-collision wave into its components. The soliton components are described by the roots of a complex analytic function that’s related to the wave so that’s where the root finding problem appears. If you're very interested there's more detail in my paper here: https://arxiv.org/abs/1509.08448 

So I implemented a quite basic rootfinding algorithm for that work and then during my PhD I read a bit more about the area, implemented a better algorithm and spun the rootfinding part out into this package. Hopefully it's useful to some people!
